# Generated by Django 5.1.1 on 2025-12-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Yetkazib beruvchi nomi')),
                ('contact_person', models.CharField(blank=True, max_length=150, null=True, verbose_name="Bog'lanuvchi shaxs")),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True, verbose_name='Elektron pochta')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Manzil')),
                ('supplier_type', models.CharField(choices=[('publisher', 'Nashriyot'), ('distributor', 'Distribyutor'), ('bookstore', "Kitob do'koni"), ('private', "Xususiy shaxs/Sovg'a")], default='distributor', max_length=50, verbose_name='Turi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yetkazib beruvchi',
                'verbose_name_plural': 'Yetkazib beruvchilar',
                'ordering': ['name'],
            },
        ),
    ]
