# Generated by Django 5.1.1 on 2025-12-07 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Kitob nomi')),
                ('author', models.CharField(max_length=255, verbose_name='Muallif')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('publication_year', models.PositiveSmallIntegerField(verbose_name='Nashr yili')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('genre', models.CharField(choices=[('fiction', 'Badiiy Adabiyot'), ('science', 'Ilmiy'), ('history', 'Tarix'), ('tech', 'Texnologiya/Dasturlash'), ('children', 'Bolalar Adabiyoti'), ('other', 'Boshqa')], default='fiction', max_length=50, verbose_name='Janr')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_added', to=settings.AUTH_USER_MODEL, verbose_name='Kiritdi')),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
                'unique_together': {('title', 'author', 'publication_year')},
            },
        ),
    ]
