# Generated by Django 5.1.1 on 2025-12-07 11:18

import borrowing.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now_add=True, verbose_name='Qarzga berilgan sana')),
                ('expected_return_date', models.DateField(default=borrowing.models.get_default_expected_return_date, verbose_name='Kutilayotgan qaytarish sanasi')),
                ('actual_return_date', models.DateField(blank=True, null=True, verbose_name='Haqiqiy qaytarish sanasi')),
                ('is_returned', models.BooleanField(default=False, verbose_name='Qaytarilgan')),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='borrowings', to='inventory.bookcopy', verbose_name='Qarzga olingan nusxa')),
                ('borrowed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_borrowings', to=settings.AUTH_USER_MODEL, verbose_name='Qarz bergan xodim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='borrowed_books', to=settings.AUTH_USER_MODEL, verbose_name='Qarz oluvchi')),
            ],
            options={
                'verbose_name': 'Qarzga berish',
                'verbose_name_plural': 'Qarzga berishlar',
            },
        ),
    ]
