# Generated by Django 5.1.1 on 2025-12-07 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_stock', models.PositiveIntegerField(default=0, verbose_name='Umumiy zaxira')),
                ('available_stock', models.PositiveIntegerField(default=0, verbose_name='Mavjud nusxalar')),
                ('on_loan', models.PositiveIntegerField(default=0, verbose_name='Qarzda')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='books.book', verbose_name='Kitob')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_updates', to=settings.AUTH_USER_MODEL, verbose_name="So'nggi yangilagan xodim")),
            ],
            options={
                'verbose_name': 'Zaxira Hisobi',
                'verbose_name_plural': 'Zaxira Hisoblari',
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_number', models.CharField(max_length=50, unique=True, verbose_name='Inventar raqami')),
                ('status', models.CharField(choices=[('available', 'Mavjud'), ('on_loan', 'Qarzga berilgan'), ('maintenance', "Ta'mirlashda"), ('lost', "Yo'qolgan")], default='available', max_length=20, verbose_name='Holati')),
                ('condition', models.CharField(default='Yaxshi', max_length=100, verbose_name='Jismoniy holat')),
                ('shelf_location', models.CharField(max_length=50, verbose_name='Javonda joylashuvi')),
                ('purchased_date', models.DateField(auto_now_add=True, verbose_name='Sotib olingan sana')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='books.book', verbose_name='Asosiy kitob')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_copies', to='inventory.inventoryitem', verbose_name='Zaxira obyekti')),
            ],
            options={
                'verbose_name': 'Kitob Nusxasi',
                'verbose_name_plural': 'Kitob Nusxalari',
            },
        ),
    ]
