# Generated by Django 5.1.1 on 2025-12-07 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name="Ob'ekt ID")),
                ('status', models.CharField(choices=[('pending', 'Kutishda'), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('flagged', 'Belgilangan')], default='pending', max_length=20, verbose_name='Holati')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Nazoratchi eslatmalari')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Kontent turi')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_actions', to=settings.AUTH_USER_MODEL, verbose_name='Nazoratchi')),
            ],
            options={
                'verbose_name': 'Kontent Nazorati',
                'verbose_name_plural': 'Kontent Nazoratlari',
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
