# Generated by Django 5.1.1 on 2025-12-07 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Yaratish'), ('update', 'Yangilash'), ('delete', "O'chirish"), ('login', 'Kirish'), ('logout', 'Chiqish'), ('borrow', 'Qarzga berish'), ('return', 'Qaytarish')], max_length=20, verbose_name='Harakat turi')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Sana va vaqt')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name="Ob'ekt ID")),
                ('changes', models.JSONField(blank=True, null=True, verbose_name="O'zgarishlar")),
                ('description', models.CharField(max_length=255, verbose_name='Tavsif')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name="Ob'ekt turi")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Harakat Jurnali',
                'verbose_name_plural': 'Harakat Jurnallari',
                'ordering': ['-timestamp'],
            },
        ),
    ]
